name:                Turtle-on-Gloss
version:             1.0.0.0
github:              "little-schemer/Turtle-on-Gloss"
license:             BSD3
author:              "little Haskeller"
maintainer:          "example@example.com"
copyright:           "2018 little Haskeller"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/little-schemer/Turtle-on-Gloss#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- optparse-applicative

library:
  source-dirs: src

executables:
  Turtle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss

  # CircleDance:
  #   main:                circleDance.hs
  #   source-dirs:         sample
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

  # DragonCurve:
  #   main:                dragonCurve.hs
  #   source-dirs:         sample
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

  # KochCurve:
  #   main:                kochCurve.hs
  #   source-dirs:         sample
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

  # Graph:
  #   main:                graph.hs
  #   source-dirs:         sample
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

  # Star:
  #   main:                star.hs
  #   source-dirs:         sample
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

  # DragonCurveL:
  #   main:                dragonCurveL.hs
  #   source-dirs:         sample/L-system
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

  # KochCurveL:
  #   main:                kochCurveL.hs
  #   source-dirs:         sample/L-system
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Turtle-on-Gloss

tests:
  Turtle-on-Gloss-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss
