name:                Turtle-on-Gloss
version:             0.1.0.0
github:              "little-schemer/Turtle-on-Gloss"
license:             BSD3
author:              "little Haskeller"
maintainer:          "example@example.com"
copyright:           "2018 little Haskeller"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/little-schemer/Turtle-on-Gloss#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  Turtle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss

  Fractal:
    main:                Main.hs
    source-dirs:         sample/fractal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss

  Spiral:
    main:                Main.hs
    source-dirs:         sample/spiral
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss

  Koch:
    main:                Main.hs
    source-dirs:         sample/koch
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss

  Dragon:
    main:                Main.hs
    source-dirs:         sample/dragonCurve
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss


  Star:
    main:                Main.hs
    source-dirs:         sample/star
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss

tests:
  Turtle-on-Gloss-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Turtle-on-Gloss
