* Turtle Graphics on Gloss

  [[http://hackage.haskell.org/package/gloss][Gloss]] を使った [[https://en.wikipedia.org/wiki/Turtle_graphics][Turtle Graphics]] です。Gloss については [[https://qiita.com/lotz/items/eb73e62a64bc208c2dd6][こちら]] の記事が参考になる
と思います。


** 含まれるファイル
   #+BEGIN_EXAMPLE
   app/Main.hs              -- 正三角形を描く

   sample
   ├─ dragonCurve/Main.hs   -- ドラゴン曲線を描く
   ├─ fractal/Main.hs       --  L-System を使ってフラクタルな図形を描く
   ├─ koch/Main.hs          --  Koch 曲線を描く
   ├─ spiral/Main.hs        --  らせんを描く
   └─ star/Main.hs          --  星を描く

   src
   ├─ L_system.hs           --  L-System
   └─ Turtle.hs             --  Turtle Graphics 本体
   #+END_EXAMPLE


** 使い方
   + ~stack build~ を実行することで sample ディレクトリ以下にあるサンプルがコン
     パイルされ、 ~Fractal, Spiral, Koch, Dragon, Star~ といったファイルが作られます。
   + ~stack exec Fractal~ や ~stack exec Spiral~ を実行すると図形が描画されます。
   + 現在のバージョンでは gloss の ~display~ 関数を使っているので、最終結果のみ
     を表示します。


** Turtle Graphics のコマンド
   亀の状態を ~TurtleST~ で表します。

   #+BEGIN_SRC haskell
     data TurtleST = TurtleST { angle    :: Float -- ^ 亀の向き
                              , point    :: Point -- ^ 亀の位置
                              , penColor :: Color -- ^ ペンの色
                              , pen      :: Bool  -- ^ up or down
                              } deriving Show
   #+END_SRC

   各コマンドの型は次のようになっています。

   #+BEGIN_SRC haskell
     type Command = TurtleST -> (Picture, TurtleST)
   #+END_SRC

   各コマンドは ~TurtleST~ を取り、図形 (Picture) とコマンド実行後の ~TurtleST~
   を返します。

*** forward n, fd n
    亀が n だけ前進する。 ペンが下りていれば線を描く。

*** backward n, bk n
    亀が n だけ後退する。 ペンが下りていれば線が描く。

*** left th, lt th
    亀が th 度だけ左旋回する。

*** right th, rt th
    亀が th 度だけ右旋回する。

*** goto p
    亀が p の位置へ移動する。亀の向きは変らない。ペンが下りていれば線を描く。

*** penDown, pd
    亀のペンを下げる。亀が移動すると線が描かれる。

*** penUp, pu
    亀のペンを上げる。亀が移動しても線は描かれない。

*** setAngle th
    亀の向きを th 度に設定する。

*** setPoint p
    亀の位置を p に設定する。

*** setColor c
    亀のペンの色を c に設定する。

*** runTurtle [Command]
    リストの中のコマンドを順に実行した図形を描くコマンドを返す。

*** drawPolygonL n m
    一辺の長さが m の正 n 角形を左回りに描く

*** drawPolygonR n m
    一辺の長さが m の正 n 角形を右回りに描く

*** drawArcL th r
    中心角 th , 半径 r の円弧を左回りに描く。

*** drawArcR th r
    中心角 th , 半径 r の円弧を右回りに描く。
